projects:
  mykaelium:
    path: ~/source/mykaelium
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim mykaelium/src/lib.rs
      slop:
        layout: even-horizontal
        panes:
          - pi
      notes:
        panes:
          - nvim notes/next.md
      scratch:

  dotfiles:
    path: ~/source/dotfiles
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi --skill .opencode/skill
      scratch:

  llm-config:
    path: ~/source/llm-config
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  pi:
    path: ~/source/pi
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi #sudo -u pi zsh -lc "pi"
      scratch:

  rwm:
    path: ~/source/rwm
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim rwm/src/lib.rs
          - pi
      scratch:

  tsp_ytdlp:
    path: ~/source/tsp_ytdlp
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim src/main.rs
          - pi
      scratch:

  nix_config:
    path: ~/source/nix_config
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim flake.nix
          - pi
      notes:
        panes:
          - nvim notes/index.md
      scratch:
      vibe:
        panes:
          - pi
      deploy:

  dwm:
    path: ~/source/dwm

  st:
    path: ~/source/st

  dmenu:
    path: ~/source/dmenu

  frostbolt:
    path: ~/source/frostbolt
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
      slop:
        layout: even-horizontal
        panes:
          - nvim .
          - pi

  agentcoder:
    path: ~/source/agent_coder

  gltf_animation-blender-plugin:
    path: ~/source/gltf_animation_layerer

  private:
    path: ~/source/private

  "TofuBerry🍓🍇":
    path: ~/source/tofuberry
    filter_out: "./target/"

  faucet 🌊:
    path: ~/source/faucet
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  Games:
    path: ~/Games
    find_override: sel=$(fd -e sh -L -d 3 | grep -v battlenet | fzf) && echo "$sel" && bash "$sel"
    find_override_root_only: true

  videos:
    path: ~/Videos/youtube
    filter_out: "(.*part|.*json)"
    handler_override: handlers/video_handler_handler.sh
    handler_pattern: ".*"
    on_enter: "mpv_play -m o"
    find_override: "mpv_play -m o"

  asm:
    path: ~/Videos/asm
    filter_out: "(.*part|.*json)"

  vw:
    path: ~/Documents/notes
    on_enter: "vw"
