projects:
  mykaelium:
    path: $SOURCE/mykaelium
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim mykaelium/src/lib.rs
      slop:
        layout: even-horizontal
        panes:
          - pi
      notes:
        panes:
          - nvim notes/next.md
      scratch:

  dotfiles:
    path: $SOURCE/dotfiles
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  llm-config:
    path: $SOURCE/llm-config
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  rwm:
    path: $SOURCE/rwm
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim rwm/src/lib.rs
          - pi
      scratch:

  tsp_ytdlp:
    path: $SOURCE/tsp_ytdlp
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim src/main.rs
          - pi
      scratch:

  nix_config:
    path: $SOURCE/nix_config
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim flake.nix
          - pi
      notes:
        panes:
          - nvim notes/index.md
      scratch:
      vibe:
        panes:
          - pi
      deploy:

  dwm:
    path: $SOURCE/dwm

  st:
    path: $SOURCE/st

  dmenu:
    path: $SOURCE/dmenu

  agentcoder:
    path: $SOURCE/agent_coder

  gltf_animation-blender-plugin:
    path: $SOURCE/gltf_animation_layerer

  private:
    path: $SOURCE/private
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  "TofuBerry🍓🍇":
    path: $SOURCE/tofuberry
    filter_out: "./target/"

  faucet 🌊:
    path: $SOURCE/faucet
    filter_out: "./target/"
    tmux_windows:
      dev:
        layout: even-horizontal
        panes:
          - nvim .
          - pi
      scratch:

  Games:
    path: ~/Games
    find_override: sel=$(fd -e sh -L -d 3 | grep -v battlenet | fzf) && echo "$sel" && bash "$sel"
    find_override_root_only: true

  videos:
    path: ~/Videos/youtube
    filter_out: "(.*part|.*json)"
    handler_override: handlers/video_handler_handler.sh
    handler_pattern: ".*"
    on_enter: "mpv_play -m o"
    find_override: "mpv_play -m o"

  asm:
    path: ~/Videos/asm
    filter_out: "(.*part|.*json)"

  vw:
    path: ~/Documents/notes
    on_enter: "vw"

  afk:
    path: ~
    find_skip: true
    tmux_windows:
      hello:
        panes:
