#!/bin/sh
case "$1" in
  next)
    tmux next-window
    count=0
    while [ "$(tmux display-message -p '#{window_name}')" = "terminal" ] && [ $count -lt 20 ]; do
      tmux next-window
      count=$((count+1))
    done
    ;;
  prev)
    tmux previous-window
    count=0
    while [ "$(tmux display-message -p '#{window_name}')" = "terminal" ] && [ $count -lt 20 ]; do
      tmux previous-window
      count=$((count+1))
    done
    ;;
  *)
    exit 1
    ;;
esac
