#!/usr/bin/env bash

target=$(tmux list-windows -F "#{window_index}: #{window_name}" \
  | grep -v "^$(tmux display-message -p "#I"):" \
  | grep -v ": terminal$" \
  | fzf-tmux -p 40%,30% --prompt="Move to: " \
  | cut -d: -f1)

if [ -n "$target" ]; then
  tmux join-pane -t :"$target"
fi
