[Interface]
# Device: grown stork
#Label: Mullvad
Address = 10.64.99.119/32,fc00:bbbb:bbbb:bb01::1:6376/128
DNS = 10.64.0.1
PostUp = wg set %i private-key /etc/wireguard/wg0.key

[Peer]
PublicKey = zX6pm3TVJe7rjQ9GrFH1IY29vw/PJL6LGh3/ALxEyx4=
AllowedIPs = 0.0.0.0/0,::0/0
Endpoint = 156.59.50.194:51820
