#!/bin/sh
userresources=$XDG_CONFIG_HOME/X11/.Xresources
usermodmap=$XDG_CONFIG_HOME/X11/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
export LUTRIS_SKIP_INIT

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ "$(basename "$WM")" = "dwm" ]; then
    ( while [ "$KILLDWM" != "true" ]; do
            dwm
    done ) &
    #xrandr --output DisplayPort-0 --off --output DisplayPort-1 --off --output DisplayPort-2 --primary --mode 2560x1440 --pos 1200x240 --rotate normal --output HDMI-A-0 --mode 1920x1200 --pos 0x0 --rotate left
    #$HOME/.screenlayout/layout.sh
    #background_set.sh
    startdwm_pid=$!
    sxhkd &
    numlockx on
    eval $(ssh-agent)
    #sleep 1
    [ "$(basename "$WM")" = "dwm" ] && [ -f "$dotfiles/dwm/dstatus.sh" ] && "$dotfiles/dwm/dstatus.sh" 1,2>/dev/null &
    $dotfiles/dwm/startup.sh &
    wait $startdwm_pid
    #sleep 10000
    #while [[ true ]]; do
    #    sleep 1 
    #done
fi 
