[Interface]
Address = 10.8.0.3/24
PostUp = wg set %i private-key /etc/wireguard/wg0.key

[Peer]
PublicKey = 38Vn6KX94Cpk99Ek5k7sB+tYWtXEZX1gaI9T8S8dXHE=
Endpoint = odri.xyz:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
