#!/bin/sh
#
# ____  _   _ _____ _     _          _    ____ _   _  ___  ____ _____ ___ ____ 
#/ ___|| | | | ____| |   | |        / \  / ___| \ | |/ _ \/ ___|_   _|_ _/ ___|
#\___ \| |_| |  _| | |   | |       / _ \| |  _|  \| | | | \___ \ | |  | | |    
# ___) |  _  | |___| |___| |___   / ___ \ |_| | |\  | |_| |___) || |  | | |___ 
#|____/|_| |_|_____|_____|_____| /_/   \_\____|_| \_|\___/|____/ |_| |___\____|
#
#command -v todobin > /dev/null && todobin #no
################
#exports:
###############
export TERM='st'
export WEB='firefox'
export BROWSER='firefox'
export EMAILCLIENT='neomutt'
export EDITOR='vim'
export VISUAL='vim'
export BIN="$HOME/bin"
export bin="$BIN"
export PATH=$PATH:$BIN #add /home/$USER/bin to path
export PATH=$PATH:"$BIN/steam_scripts" #and subfolder for steam scripts
export PATH=$HOME/bin:$PATH:$HOME/.local/bin
export dl="$HOME/Downloads"
export CARGO_ASC=true
export GDUSER="~/.local/share/godot/app_userdata/Mykaelium/"
export GTK_THEME=Arc-Dark
export XCURSOR_THEME=Arc-Dark
export GODOT4_BIN=/bin/godot-mono-bin
export SOURCE="$HOME/source"
export PASSWORD_STORE_GENERATED_LENGTH=30
export QMK="$SOURCE/qmk_firmware"
systemctl --user import-environment PATH HOME USER #DISPLAY defined in $dotifles/dwm/startup.sh

################
#Extras
################
[ -e ~/.cargo/env ] && . ~/.cargo/env 
#export WORKON_HOME="/home/maxwell/pyvenv" #cant nest variables this is a hack to let emacs load successfully
export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab

################
#Functions:
################
pd() { pandoc -T Plain "$1"| less; }
hfiglet () { figlet "$@" | sed -n "s/.*/\# &/p"; }
kn() { pgrep $@ | xargs kill -9 }

#Addtional keybindings:
#bindkey -s '^t' 'st & disown\nclear\n' #st in pwd
bindkey -s 'C-c' 'kill -9 !%' #ruthless version of standard ctrl-c => should always kill the process rather than asking the process to shut down nicely
################
#Aliases:
###############
#type fzf >> /dev/null && type fd >> /dev/null 
alias cat='bat'
alias crontab='VISUAL=vim && crontab'
alias myip='curl ipinfo.io/ip'
alias zshrc="vim ~/.zshrc && source ~/.zshrc"
alias bashrc="vim ~/.bashrc && source ~/.bashrc"
alias shrc="vim ~/.config/sh/shrc && source ~/.config/sh/shrc"
alias sxhkdrc="vim ~/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd"
alias bspwmrc="vim ~/.config/bspwm/bspwmrc && pkill -USR1 -x sxhkd"
#alias lastupdated = "awk 'END{sub(/\[/,""); print $1}' /var/log/pacman.log"
alias bashrctag="vim ~/.bashrc_extra && source ~/.bashrc"
alias zshrctag="vim ~/.zshrc_extra && source ~/.zshrc_extra"
alias bashprofile="vim ~/.bash_profile"
alias zprofile="vim ~/.zprofile"
alias xrc="vim $XDG_CONFIG_HOME/X11/xinitrc"
alias xres="vim ~/.Xresources && xrdb ~/.Xresources"
type nvim  >>/dev/null && alias vimrc='PREV_DIR=$(pwd) && cd ~/.config/nvim/ && vim init.vim && cd $PREV_DIR' || alias vimrc='vim ~/.vimrc'
alias vw='PREV_DIR=$(pwd) && cd ~/vimwiki && vim index.wiki && cd $PREV_DIR'
alias tmuxrc="vim ~/.tmux.conf"
alias emacsrc="vim ~/.emacs.d/init.el"
alias i3rc="vim $dotfiles/.config/i3/config.base && $dotfiles/makesymlinks.sh $dotfiles_tag >> /dev/null && i3-msg reload"
alias bm="vim $dotfiles/scripts/web_bookmarks.json"
alias dunstrc="vim ~/.config/dunst/dunstrc"
alias i3tag="vim $dotfiles/.config/i3/config.extra && $dotfiles/makesymlinks.sh $dotfiles_tag >> /dev/null && i3-msg reload"
alias termrc="vim ~/.config/terminator/config"
alias i3sbar="vim ~/.config/i3status/config && i3-msg restart"
alias zathurarc="vim ~/.config/zathura/zathurarc"
alias rofirc="vim ~/.config/rofi/config.rasi"
alias sys="sudo systemctl"
alias dl="cd ~/Downloads"
alias p="sudo pacman"
alias picomrc="vim ~/.config/picom/picom.conf"
alias muttrc="vim ~/.config/mutt/muttrc"
alias mutt='cd ~/attach && neomutt -e "source ~/.config/mutt/accounts/1-maxwell@odri.net.au.muttrc"'
alias mwrc='sudo vim /usr/share/mutt-wizard'
alias newsboatrc="vim ~/.config/newsboat/config"
alias url="vim ~/.config/newsboat/urls"
alias dragon="dragon-drag-and-drop"
alias rmdir='rmdir -p'

alias mpdrc="vim ~/.config/mpd/mpd.conf"
alias ncmpcpprc="vim ~/.config/ncmpcpp/config"
alias ncm="ncmpcpp"
#alias ytdl="yt-dlp --abort-on-unavailable-fragment"
alias ytdl='yt-dlp --restrict-filenames --abort-on-unavailable-fragment --trim-filenames 225 -o "~/Downloads/ytdlp/%(title)s.%(ext)s" --write-info-json'
alias tsm='transmission-remote --torrent-done-script ~/bin/torrdone'
alias tsmr='transmission-remote -l | grep -v 'Queued''
alias tsmd="transmission-remote -l | grep 100% | awk '{print $1}' | tr -d '\*' | tr '\n' ', ' | sed 's/,\ $/\n/' | sed 's/,$/\n/' | xargs -I {} transmission-remote -t '{}' -r"
alias ex='exit'
alias sshez='ORIGINAL_HOME=$HOME && sshfs maxwell@donpablito:/ ~/media/donpablito && HOME=~/media/donpablito/home/maxwell zsh -c '\''cd $HOME; exec zsh'\'' && umount ~/media/donpablito && HOME=$ORIGINAL_HOME'
#alias mpvr="find . -maxdepth 1 | shuf | grep -x . -v | xargs mpv"
##Better handles irregular file names e.g. spaces/hyphens/other special characters
#mpvr() {
# # Read filenames into an array, shuffle them with shuf, and store in 'files'
#  mapfile -t -d $'\0' files < <(find . -maxdepth 1 -print0 | shuf -z)
#
#  # Play shuffled files with mpv
#  mpv "${files[@]}"
#}
#alias mpvr='find . -maxdepth 1 -print0 | shuf -z | xargs -0 mpv'
alias mpvr='fd . --print0 | shuf --zero-terminated | xargs -0 mpv'
alias mpvo='fd . --print0 | xargs -0 mpv'
alias mkdir="mkdir -pv"
alias mpvr='$bin/mpv_play -m r'
alias mpvs='$bin/mpv_play -m s'
alias mpvo='$bin/mpv_play -m o'
#alias lss='ls'
#type exa >/dev/null && alias ls="exa --color=auto -hal --group-directories-first"
#type exa >/dev/null && alias lt="exa --color=auto -hal --group-directories-first"
#type exa >/dev/null && alias ls="exa --color=auto -h --group-directories-first"
#type exa >/dev/null && alias l="exa --color=auto -h --group-directories-first"
#type exa >/dev/null && alias lsa="exa --color=auto -ha --group-directories-first"
alias ls="/bin/ls -h --color=auto --group-directories-first"
alias lls="/bin/ls"
alias grep="grep --color=auto"
alias mv="mv -v"
alias cp="cp -v"
alias pacs="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias alp="vim $dotfiles/archlinux_x86_64_packages"
alias dfn="df -h | grep -vE 'run|tmpfs|efivars|efi' | awk '!/dev[[:space:]]/' | tail -n +1" #tail to remove whitespace above header

alias untar='tar -zxvf'
alias screensave="xclip -selection clipboard -target image/png -out > out.png"

command -v ytop > /dev/null && alias htop="ytop -asm -c monokai"

alias USB="/home/maxwell/media/usb"
