#!/bin/sh
#
# ____  _   _ _____ _     _          _    ____ _   _  ___  ____ _____ ___ ____ 
#/ ___|| | | | ____| |   | |        / \  / ___| \ | |/ _ \/ ___|_   _|_ _/ ___|
#\___ \| |_| |  _| | |   | |       / _ \| |  _|  \| | | | \___ \ | |  | | |    
# ___) |  _  | |___| |___| |___   / ___ \ |_| | |\  | |_| |___) || |  | | |___ 
#|____/|_| |_|_____|_____|_____| /_/   \_\____|_| \_|\___/|____/ |_| |___\____|
#
todobin
################
#exports:
###############
export TERM='st'
export WEB='firefox'
export BROWSER='firefox'
export EMAILCLIENT='neomutt'
export EDITOR='vim'
export VISUAL='vim'
export BIN="$HOME/bin"
export bin="$BIN"
export PATH=$PATH:$BIN #add /home/$USER/bin to path
export PATH=$PATH:"$BIN/steam_scripts" #and subfolder for steam scripts
export PATH=$HOME/bin:$PATH:$HOME/.local/bin
export dl="$HOME/Downloads"
export game="$HOME/source/game"
export torr="$HOME/media/xd/torrents"


################
#Extras
################
[ -e ~/.cargo/env ] && . ~/.cargo/env 
export WORKON_HOME="/home/maxwell/pyvenv" #cant nest variables this is a hack to let emacs load successfully
export JUPYTERLAB_DIR=$HOME/.local/share/jupyter/lab

################
#Functions:
################
pd() { pandoc -T Plain "$1"| less; }
hfiglet () { figlet "$@" | sed -n "s/.*/\# &/p"; }
kn() { pgrep $@ | xargs kill -9 }

#Addtional keybindings:
#bindkey -s '^t' 'st & disown\nclear\n' #st in pwd
bindkey -s 'C-c' 'kill -9 !%' #ruthless version of standard ctrl-c => should always kill the process rather than asking the process to shut down nicely
################
#Aliases:
###############
#type fzf >> /dev/null && type fd >> /dev/null 
alias cat='bat'
alias crontab='VISUAL=vim && crontab'
alias dfn='df -h | egrep "Filesystem|nvme|sd"'
alias myip='curl ipinfo.io/ip'
alias zshrc="vim ~/.zshrc && source ~/.zshrc"
alias bashrc="vim ~/.bashrc && source ~/.bashrc"
alias shrc="vim ~/.config/sh/shrc && source ~/.config/sh/shrc"
alias sxhkdrc="vim ~/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd"
alias bspwmrc="vim ~/.config/bspwm/bspwmrc && pkill -USR1 -x sxhkd"
alias bashrctag="vim ~/.bashrc_extra && source ~/.bashrc"
alias zshrctag="vim ~/.zshrc_extra && source ~/.zshrc_extra"
alias bashprofile="vim ~/.bash_profile"
alias zprofile="vim ~/.zprofile"
alias xrc="vim ~/.xinitrc"
alias xres="vim ~/.Xresources && xrdb ~/.Xresources"
type nvim  >>/dev/null && alias vimrc='PREV_DIR=$(pwd) && cd ~/.config/nvim/ && vim init.vim && cd $PREV_DIR' || alias vimrc='vim ~/.vimrc'
alias vw='PREV_DIR=$(pwd) && cd ~/vimwiki && vim index.wiki && cd $PREV_DIR'
alias tmuxrc="vim ~/.tmux.conf"
alias emacsrc="vim ~/.emacs.d/init.el"
alias i3rc="vim $dotfiles/.config/i3/config.base && $dotfiles/makesymlinks.sh $dotfiles_tag >> /dev/null && i3-msg reload"
alias bm="vim $dotfiles/scripts/web_bookmarks.txt"
alias dunstrc="vim ~/.config/dunst/dunstrc"
alias i3tag="vim $dotfiles/.config/i3/config.extra && $dotfiles/makesymlinks.sh $dotfiles_tag >> /dev/null && i3-msg reload"
alias termrc="vim ~/.config/terminator/config"
alias i3sbar="vim ~/.config/i3status/config && i3-msg restart"
alias zathurarc="vim ~/.config/zathura/zathurarc"
alias rofirc="vim ~/.config/rofi/config.rasi"
alias sys="sudo systemctl"
alias dl="cd ~/Downloads"
alias p="sudo pacman"
alias picomrc="vim ~/.config/picom/picom.conf"
alias muttrc="vim ~/.config/mutt/muttrc"
alias mutt='cd ~/attach && neomutt -e "source ~/.config/mutt/accounts/1-maxwell@odri.net.au.muttrc"'
alias mwrc='sudo vim /usr/share/mutt-wizard'
alias newsboatrc="vim ~/.config/newsboat/config"
alias url="vim ~/.config/newsboat/urls"
alias dragon="dragon-drag-and-drop"

alias mpdrc="vim ~/.config/mpd/mpd.conf"
alias ncmpcpprc="vim ~/.config/ncmpcpp/config"
alias ncm="ncmpcpp"
alias ytdl="youtube-dl --abort-on-unavailable-fragment"
alias tsm='transmission-remote --torrent-done-script ~/bin/torrdone'
alias tsmr='transmission-remote -l | grep -v 'Queued''
alias tsmd="transmission-remote -l | grep 100%"
alias mpvr="find . -maxdepth 1 | shuf | grep -x . -v | xargs mpv"

alias mkdir="mkdir -pv"
alias lss='ls'
type exa >/dev/null && alias ls="exa --color=auto -hal --group-directories-first"
type exa >/dev/null && alias lt="exa --color=auto -hal --group-directories-first"
type exa >/dev/null && alias ls="exa --color=auto -h --group-directories-first"
type exa >/dev/null && alias l="exa --color=auto -h --group-directories-first"
type exa >/dev/null && alias lsa="exa --color=auto -ha --group-directories-first"
alias lls="/bin/ls"
alias grep="grep --color=auto"
alias mv="mv -v"
alias cp="cp -v"
alias pacs="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias alp="vim $dotfiles/archlinux_x86_64_packages"
alias dfn='df -h | egrep "Filesystem|nvme|sd"'
alias untar='tar -zxvf'
alias screensave="xclip -selection clipboard -target image/png -out > out.png"

command -v ytop > /dev/null && alias htop=ytop

alias USB="/home/maxwell/media/usb"
