#!/bin/sh
#
# ____  _   _ _____ _     _          _    ____ _   _  ___  ____ _____ ___ ____ 
#/ ___|| | | | ____| |   | |        / \  / ___| \ | |/ _ \/ ___|_   _|_ _/ ___|
#\___ \| |_| |  _| | |   | |       / _ \| |  _|  \| | | | \___ \ | |  | | |    
# ___) |  _  | |___| |___| |___   / ___ \ |_| | |\  | |_| |___) || |  | | |___ 
#|____/|_| |_|_____|_____|_____| /_/   \_\____|_| \_|\___/|____/ |_| |___\____|
#
#command -v todobin > /dev/null && todobin #no
################
#exports:
###############
export TERM='alacritty'
export WEB='firefox'
export BROWSER='firefox'
export EMAILCLIENT='neomutt'
export EDITOR='vim'
export VISUAL='vim'
export BIN="$HOME/bin"
export bin="$BIN"
export dl="$HOME/Downloads"
export CARGO_ASC=true
export GDUSER="$HOME/.local/share/godot/app_userdata/Mykaelium/"
export GTK_THEME=Arc-Dark
export XCURSOR_THEME=Arc-Dark
export GODOT4_BIN=/bin/godot-mono-bin
export SOURCE="$HOME/source"
export PASSWORD_STORE_GENERATED_LENGTH=30
export QMK="$SOURCE/qmk_firmware"
export JUPYTERLAB_DIR="$HOME/.local/share/jupyter/lab"
export PATH="$BIN:$BIN/steam_scripts:$HOME/.local/share/cargo/bin:$HOME/.local/bin:$PATH"
export MANPAGER='nvim +Man!'
command -v systemctl >/dev/null 2>&1 && systemctl --user import-environment PATH HOME USER XDG_CONFIG_HOME BIN

################
#Functions:
################
pd() { pandoc -T Plain "$1"| less; }
hfiglet () { figlet "$@" | sed -n "s/.*/\# &/p"; }

#Addtional keybindings:
#bindkey -s '^t' 'st & disown\nclear\n' #st in pwd
# Only run bindkey if we're in a Zsh shell
if [ -n "$ZSH_VERSION" ]; then
    bindkey -s 'C-c' 'kill -9 !%' #ruthless version of standard ctrl-c => should always kill the process rather than asking the process to shut down nicely
fi
################
#Aliases:
###############
#type fzf >> /dev/null && type fd >> /dev/null 
alias cat='bat'
alias crontab='VISUAL=vim && crontab'
alias myip='curl ipinfo.io/ip'
alias zshrc="vim ~/.zshrc && source ~/.zshrc"
alias bashrc="vim ~/.bashrc && source ~/.bashrc"
alias shrc="vim ~/.config/sh/shrc && source ~/.config/sh/shrc"
alias sxhkdrc="vim ~/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd"
alias bspwmrc="vim ~/.config/bspwm/bspwmrc && pkill -USR1 -x sxhkd"
alias faucetrc="vim ~/.config/faucet/faucet.yaml"
alias alrc="vim ~/.config/alacritty/alacritty.toml"
#alias lastupdated = "awk 'END{sub(/\[/,""); print $1}' /var/log/pacman.log"
alias bashrctag="vim ~/.bashrc_extra && source ~/.bashrc"
alias zshrctag="vim ~/.zshrc_extra && source ~/.zshrc_extra"
alias bashprofile="vim ~/.bash_profile"
alias zprofile="vim ~/.zprofile"
alias xrc="vim \$XDG_CONFIG_HOME/X11/xinitrc"
alias xres="vim ~/.Xresources && xrdb ~/.Xresources"
alias path="realpath"
if type nvim >/dev/null 2>&1; then
    alias vimrc='PREV_DIR=$(pwd) && cd ~/.config/nvim/ && nvim init.vim && cd "$PREV_DIR"'
else
    alias vimrc='vim ~/.vimrc'
fi
#alias vw='PREV_DIR=$(pwd) && cd ~/Documents/notes && nvim index.md && cd $PREV_DIR'
alias swrc='$EDITOR "${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/sw.yaml"'
tmuxrc() {
    $EDITOR "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" && \
    tmux source-file "${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" 2>/dev/null
}
alias emacsrc="vim ~/.emacs.d/init.el"
alias i3rc="vim \$dotfiles/.config/i3/config.base && \$dotfiles/makesymlinks.sh \$dotfiles_tag >> /dev/null && i3-msg reload"
alias bm="vim \$dotfiles/scripts/web_bookmarks.json"
alias dunstrc="vim ~/.config/dunst/dunstrc"
alias i3tag="vim \$dotfiles/.config/i3/config.extra && \$dotfiles/makesymlinks.sh \$dotfiles_tag >> /dev/null && i3-msg reload"
alias termrc="vim ~/.config/terminator/config"
alias i3sbar="vim ~/.config/i3status/config && i3-msg restart"
alias zathurarc="vim ~/.config/zathura/zathurarc"
alias rofirc="vim ~/.config/rofi/config.rasi"
alias sys="sudo systemctl"
alias dl="cd ~/Downloads"
alias p="sudo pacman"
alias picomrc="vim ~/.config/picom/picom.conf"
alias muttrc="vim ~/.config/mutt/muttrc"
alias mutt='cd ~/attach && neomutt -e "source ~/.config/mutt/accounts/1-maxwell@odri.net.au.muttrc"'
alias mwrc='sudo vim /usr/share/mutt-wizard'
alias newsboatrc="nvim ~/.config/newsboat/config"
alias url="nvim ~/.config/newsboat/urls"
alias dragon="dragon-drag-and-drop"
alias rmdir='rmdir -p'
strip_rust_doc_comments() {
  sed 's@^[ \t]*///.*$@@g' "$@"
}

alias mpdrc="vim ~/.config/mpd/mpd.conf"
alias vimpcrc="vim ~/.config/vimpc/vimpcrc"
ytdl () {
    dir=""
    urls=""
    pwd_flag=false
    dir_flag=false
    while [ "$#" -gt 0 ]
    do
        case "$1" in
            --dir) 
                if [ "$pwd_flag" = true ]
                then
                    echo "Error: Cannot use both --pwd and --dir options."
                    return 1
                fi
                dir_flag=true
                dir="$2"
                if [ ! -d "$dir" ]
                then
                    echo "Error: Directory '$dir' does not exist."
                    return 1
                fi
                dir=$(realpath "$dir")
                shift 2 ;;
            --pwd)
                if [ "$dir_flag" = true ]
                then
                    echo "Error: Cannot use both --pwd and --dir options."
                    return 1
                fi
                pwd_flag=true
                dir="$PWD"
                shift ;;
            *) 
                # Add URL to space-separated list
                urls="${urls:+$urls }$1"
                shift ;;
        esac
    done
    if [ -z "$urls" ]
    then
        echo "Error: No URLs supplied."
        return 1
    fi
    [ -z "$dir" ] && dir="$HOME/Downloads/ytdlp"
    
    # Process URLs
    old_IFS="$IFS"
    IFS=" "
    for url in $urls
    do
        yt-dlp --restrict-filenames --abort-on-unavailable-fragment --trim-filenames 225 -o "$dir/%(title)s.%(ext)s" "$url"
    done
    IFS="$old_IFS"
}
alias tsm='transmission-remote --torrent-done-script ~/bin/torrdone'
alias tsmr='transmission-remote -l | grep -v 'Queued''
#alias tsmd='transmission-remote -l | grep 100% | awk "{print $1}" | tr -d '\*' | tr '\n' ', ' | sed 's/,\ $/\n/' | sed 's/,$/\n/' | xargs -I {} transmission-remote -t '{}' -r'
tsmd() {
    transmission-remote -l | grep 100% | awk '{print $1}' | tr -d '\*' | tr '\n' ', ' | sed 's/,\ $/\n/' | sed 's/,$/\n/' | xargs -I {} transmission-remote -t '{}' -r
}
alias ex='exit'
alias sshez='ORIGINAL_HOME=$HOME && sshfs maxwell@donpablito:/ ~/media/donpablito && HOME=~/media/donpablito/home/maxwell zsh -c '\''cd $HOME; exec zsh'\'' && umount ~/media/donpablito && HOME=$ORIGINAL_HOME'
#alias mpvr="find . -maxdepth 1 | shuf | grep -x . -v | xargs mpv"
##Better handles irregular file names e.g. spaces/hyphens/other special characters
#mpvr() {
# # Read filenames into an array, shuffle them with shuf, and store in 'files'
#  mapfile -t -d $'\0' files < <(find . -maxdepth 1 -print0 | shuf -z)
#
#  # Play shuffled files with mpv
#  mpv "${files[@]}"
#}
#alias mpvr='find . -maxdepth 1 -print0 | shuf -z | xargs -0 mpv'
alias mpvr='fd . --print0 | shuf --zero-terminated | xargs -0 mpv'
alias mpvo='fd . --print0 | xargs -0 mpv'
alias mkdir="mkdir -v"
alias mpvr='$bin/mpv_play -m r'
alias mpvs='$bin/mpv_play -m s'
alias mpvo='$bin/mpv_play -m o'
alias mpvw='mpv --pause --no-fullscreen'
#alias lss='ls'
#type exa >/dev/null && alias ls="exa --color=auto -hal --group-directories-first"
#type exa >/dev/null && alias lt="exa --color=auto -hal --group-directories-first"
#type exa >/dev/null && alias ls="exa --color=auto -h --group-directories-first"
#type exa >/dev/null && alias l="exa --color=auto -h --group-directories-first"
#type exa >/dev/null && alias lsa="exa --color=auto -ha --group-directories-first"
alias ls="/bin/ls -h --color=auto --group-directories-first"
alias lls="/bin/ls"
alias grep="grep --color=auto"
alias mv="mv -v"
alias cp="cp -v"
alias pacs="pacman -Slq | fzf -m --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias alp="vim \$dotfiles/archlinux_x86_64_packages"
alias dfn="df -h | grep -vE 'run|tmpfs|efivars|efi' | awk '!/dev[[:space:]]/' | tail -n +1" #tail to remove whitespace above header

alias untar='tar -zxvf'
alias screensave="xclip -selection clipboard -target image/png -out > out.png"

command -v ytop > /dev/null && alias htop="ytop -asm -c monokai"

alias USB="/home/maxwell/media/usb"
