#!/bin/bash
volume=$(mpc --host="$HOME/.config/mpd/socket" volume "$1" | grep -oP 'volume:\s*\K\d+')
if [ "$1" -gt 0 ]; then
    notify-send -t 1200 "mpd volume 🔊 $volume%" -h string:x-canonical-private-synchronous:mpd-volume
else
    notify-send -t 1200 "mpd volume 🔈 $volume%" -h string:x-canonical-private-synchronous:mpd-volume
fi
