#!/bin/sh
#clear clipboard after 30 seconds if not overwritten already
prev_clipboard=$(xclip -sel clipboard -o)
sleep 15s && test "$(xclip -sel clipboard -o)" = "$prev_clipboard" && echo "" | xclip -sel clipboard -i && pgrep -x dunst >/dev/null && notify-send -t 700  "Clipboard cleared"
