#!/bin/sh
if ! ps -e -o args | grep -q '^emacs --daemon$'; then
    [ ! "$1" = "startup" ] && notify-send -t 1250 "Starting emacs daemon 🤗"
    emacs --daemon
    [ ! "$1" = "startup" ] && emacsclient -c &
else
    emacsclient -c &
fi
