#!/bin/sh

if [ "$XDG_SESSION_TYPE" = "wayland" ] || [ -n "$WAYLAND_DISPLAY" ]; then
    wl-copy -c 2>/dev/null
else
    xclip -selection clipboard < /dev/null
fi

if [ "$dotfile_tag" == "pc" ]; then
    emoji=$({ grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | dmenu -i -l 40 -b | awk '{print $1}' | tr -d '\n')
else
    emoji=$({ grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | dmenu -i -l 25 -b | awk '{print $1}' | tr -d '\n')
fi
if [ "$emoji" != "" ] && { grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | awk '{print $1}' | grep -Fxq "$emoji"; then
    echo $emoji | tr -d "\n" | tr -d " " | xclip -selection clipboard && pgrep -x dunst >/dev/null && notify-send -t 700 "$(xclip -o -selection clipboard) => clipboard"
fi
echo "$emoji"
