#!/bin/sh

. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/shutil.sh"

dmenu=$(get_dmenu)

printf '' | clipboard

if [ "$dotfile_tag" == "pc" ]; then
    emoji=$({ grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | $dmenu -i -l 40 -b | awk '{print $1}' | tr -d '\n')
else
    emoji=$({ grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | $dmenu -i -l 25 -b | awk '{print $1}' | tr -d '\n')
fi
if [ "$emoji" != "" ] && { grep '^[^ ]* @' "$HOME/bin/unicode_fmt"; grep -v '^[^ ]* @' "$HOME/bin/unicode_fmt"; } | awk '{print $1}' | grep -Fxq "$emoji"; then
    echo $emoji | tr -d "\n" | tr -d " " | clipboard && pgrep -x dunst >/dev/null && notify-send -t 700 "$emoji => clipboard"
fi
echo "$emoji"
