#! /usr/bin/env python3
#Searches websites by parsing command line arguments - useful when being called via dmenu
import subprocess 
import sys
import re

def websearch(args):
    #assume args is list of strings 
    args_str = '?q='+re.sub(' ','+',''.join(args))
    #
    #
    # see https://duckduckgo.com/params for customising the search params:
    #lol this shit makes ddg take forever if you enable everything
    params = {}
    #params['lang'] = 'kl=au-en'
    #params['safe_search'] = 'kp=-1'
    #params['open_instant_answers'] = 'kz=1'
    #params['autload_images'] = 'kc=1'
    #params['autoload_results'] = 'kav=1'
    #params['https'] = 'kh=1'
    #params['video_playbacl'] = 'k5=2'
    #params['color_header'] = 'kj=d' #green
    #params['color_URL'] = 'kx=g' #green
    #params['color_background'] = 'k7=p' #purple
    #params['color_text'] = 'k8=g' #default, dark grey
    #params['color_links'] = 'k9=b'#blue 
    #params['color_visited_links'] = 'kaa=p' #
    #params['color_theme'] = 'kae=t' #t for terminal, r for retro, d for dark
    #params['size'] = 'ks=n' #large textsize
    #params['width'] = 'kw=n' #normal
    #params['placement'] = 'km=m' #middle
    #params['link_font'] = 'ka=comic-sans' #meme
    #params['underline'] = 'ku=1' #on
    #params['text_font'] = 'kt=comic-sans'
    #params['instant_answers'] = 'ko=1' #on & floating
    #params['advertisments'] = 'k1=-1'  #off 
    #params['page#'] = 'kv=1' #page_nums on
    #params['units_of_measure'] = 'kaj=m' #metric
    #params['source'] = 't=trisquel' #$$$$ for GNU
    #
    #
    params_str = '' 
    for i in params:
        if len(params) != 0:
            params_str = params_str+'&'+params[i]
    firefox_URL = 'https://duckduckgo.com/'+args_str+params_str   #get rid of param_str to use default search params 
    return firefox_URL


#Main Script:
web_bookmarks_path = "/home/maxwell/bin/web_bookmarks.txt" #path to bookmarks file 
if len(sys.argv) == 1:
    print("len 1")
    subprocess.call(['firefox','-new-tab'])
    exit()
args = ' '.join(sys.argv[1:])
# ! is a duckduckgo bang, # is for for searching the web, override bookmarks.
try:
    if '!' == args[0]:
        firefox_URL = websearch(args)
    else:
        #check for bookmarks:
        print('a')
        exec(open(web_bookmarks_path).read())
        print('b')
        if args not in web_bookmarks:
            firefox_URL = websearch(args)
        else:
            firefox_URL = web_bookmarks[args]
#run firefox with URL:
#print("firefox_URL:",firefox_URL)
    subprocess.call(['firefox','-new-tab', firefox_URL])
except: 
    subprocess.call(['firefox','-new-tab'])
