#!/bin/sh

interact ()
{
    file=$1
    [ -z "$file" ] && return
    echo $(realpath $file)

    if [ -f "$file" ]; then
        # Check MIME type for text and open in Vim if it's a text file
        if file --mime-type "$file" | grep -q 'text/'; then
            if git -C "$(dirname "$file")" status > /dev/null 2>&1; then
                # Get the Git root directory and change to it
                git_root=$(git -C "$(dirname "$file")" rev-parse --show-toplevel)
                cd_path="$git_root"

                # Check for Godot project by presence of project.godot file
                if [ -f "$git_root/project.godot" ]; then
                    nvimd "$file"
                else
                    vim "$file"
                fi
            else
                vim "$file"
            fi
        else
            # Otherwise use the default application
            (nohup xdg-open "$file" >/dev/null 2>&1 &)
        fi
    fi
}

prev_dir=$(pwd)

# Check if we are in a Git repository
if git -C "$prev_dir" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    # If in Git repo, cd to the root of the repository
    cd_path=$(git -C "$prev_dir" rev-parse --show-toplevel)
    cd "$cd_path"
else
    # If not in Git repo, cd to $HOME
    cd $HOME
fi

# Get file using fzf and fd, excluding "Games" directory
files=$(fd . $prev_dir | fd -E $prev_dir | fzf -m)

#TODO: if selecting multiple files of the same type, we end up opening the same program multiple times instead of combining them

# Loop over each selected file
echo "$files" | while IFS= read -r file; do
    # If file exists, get its real path
    [ -f "$file" ] && file=$(realpath "$file")
    
    # Interact with the file
    interact "$file"
done
