#!/bin/sh
if [ -z "$1" ]; then

    [ "$WMNAME" = "dwm" ] && pkill -9 -t "tty$XDG_VTNR"
    [ "$WMNAME" = "i3" ] && i3-msg exit && sleep 1 && exit
else 
    NUMBER=$(echo "$1" | tr -dc '0-9')
    [ -n "$NUMBER" ] && pkill -9 -t "tty$NUMBER"
fi

