#!/bin/sh
#current=$(free | grep Mem | awk '{print $3}')
#total=$(free | grep Mem | awk '{print $2}')
#echo "Total: $total Current: $current"
#printf %.0f $(echo "$current/$total * 100" |  bc -l)
#printf %.2f $(echo "$float/1.18" | bc -l)
free -m | awk '/Mem:/ {printf "%.0f\n", ($2-$7)/$2*100}'
