#!/bin/sh

[ -z "$dotfiles" ] && echo "Error: \$dotfiles is not defined" && exit 1

template=""
script_name=""

while [ $# -gt 0 ]; do
    case "$1" in
        --template)
            template="$2"
            shift 2
            ;;
        *)
            script_name="$1"
            shift
            ;;
    esac
done

[ -z "$script_name" ] && echo 'Usage: newscript [--template <file>] "script_name"' && exit

if [ ! -f "$dotfiles/scripts/$script_name" ]; then
    if [ -n "$template" ] && [ -f "$template" ]; then
        cp "$template" "$dotfiles/scripts/$script_name"
    else
        echo "#!/bin/sh" > "$dotfiles/scripts/$script_name"
    fi
    chmod +x "$dotfiles/scripts/$script_name"
    vim "$dotfiles/scripts/$script_name"
    "$dotfiles/helper_scripts/custom_bin_scripts.sh"
else
    vim "$dotfiles/scripts/$script_name"
fi
