#!/bin/sh

# Resolve the path for $1
if [ "$1" = "." ]; then
    file_path="$PWD"
elif [ "$1" = ".." ]; then
    file_path="$(dirname "$PWD")"
else
    file_path="$1"
fi
# Check if $1 is a file
if [ -f "$file_path" ]; then
    # If $1 is a file, pass $2 and $3 as well
    $dotfiles/dwm/neovim-server-runner.py "$file_path" "$2" "$3"
else
    # If $1 is not a file, only pass $1 (resolved path)
    $dotfiles/dwm/neovim-server-runner.py "$file_path"
fi
