#!/bin/sh

daemon_pid=$($dotfiles/dwm/neovim-server-runner.py --query | tail -n 1)

# Check if the PID is 0, indicating the daemon is not running
if [ "$daemon_pid" -eq 0 ]; then
    # Start the daemon in a new session and redirect output to /dev/null
    setsid $dotfiles/dwm/neovim-server-runner.py --daemon > /dev/null 2>&1 &
    # Sleep for 0.2 seconds to allow the daemon to initialize
    sleep 0.2
fi

# Resolve the path for $1
if [ "$1" = "." ]; then
    file_path="$PWD"
elif [ "$1" = ".." ]; then
    file_path="$(dirname "$PWD")"
else
    file_path="$1"
fi

# Default $2 and $3 to 0 if they are not set
line_number="${2:-0}"
column_number="${3:-0}"

# Check if $file_path is a file
if [ -f "$file_path" ]; then
    # If $file_path is a file, pass $file_path, $line_number, and $column_number
    $dotfiles/dwm/neovim-server-runner.py --client "$file_path" "$line_number" "$column_number"
else
    # If $file_path is not a file, only pass $file_path
    $dotfiles/dwm/neovim-server-runner.py --client "$file_path"
fi
