#!/bin/sh

# Resolve the path for $1
if [ "$1" = "." ]; then
    file_path="$PWD"
elif [ "$1" = ".." ]; then
    file_path="$(dirname "$PWD")"
else
    file_path="$1"
fi

# Default $2 and $3 to 0 if they are not set
line_number="${2:-0}"
column_number="${3:-0}"

# Check if $file_path is a file
if [ -f "$file_path" ]; then
    # If $file_path is a file, pass $file_path, $line_number, and $column_number
    $dotfiles/dwm/neovim-server-runner.py --client "$file_path" "$line_number" "$column_number"
else
    # If $file_path is not a file, only pass $file_path
    $dotfiles/dwm/neovim-server-runner.py --client "$file_path"
fi
