#!/bin/sh
. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/shutil.sh"
[ -z "$1" ] && echo 'Usage: paper "/path/to/wallpaper/image"' && exit
[ -e "$1" ] && wal -i "$1" && echo "hi" && cd "$SOURCE/dwm" && echo "hello" && run_elevated make clean install && pkill dwm
