#!/usr/bin/env bash
#
#shopt -s nullglob globstar
#
#typeit=0
#if [[ $1 == "--type" ]]; then
#	typeit=1
#	shift
#fi
#
#if [[ -n $WAYLAND_DISPLAY ]]; then
#	dmenu=dmenu-wl
#	xdotool="ydotool type --file -"
#elif [[ -n $DISPLAY ]]; then
#	dmenu=dmenu
#	xdotool="xdotool type --clearmodifiers --file -"
#else
#	echo "Error: No Wayland or X11 display detected" >&2
#	exit 1
#fi
#
#prefix=${PASSWORD_STORE_DIR-~/.password-store}
#password_files=( "$prefix"/**/*.gpg )
#password_files=( "${password_files[@]#"$prefix"/}" )
#password_files=( "${password_files[@]%.gpg}" )
#
#password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")
#echo $password
#[[ -n $password ]] || echo "exit" && exit
#
#echo "a"
#if [[ $typeit -eq 0 ]]; then
#	#pass show -c "$password" 2>/dev/null
#	passcmd=""
#	echo "$password" | grep -E "otp/" > /dev/null  && passcmd="otp"
#	#TODO add steamguard support using steamguard-cli
#	pass $passcmd show "$password" | xclip -i -sel clip & setsid setsid async_clear_clipboard 
#	
#else
#	notify-send "Something went horribly wrong in pass"
#	#pass show "$password" | grep -v "otpauth" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool && async_clear_clipboard
#fi
shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

if [[ -n $WAYLAND_DISPLAY ]]; then
	dmenu=dmenu-wl
	xdotool="ydotool type --file -"
elif [[ -n $DISPLAY ]]; then
	dmenu=dmenu
	xdotool="xdotool type --clearmodifiers --file -"
else
	echo "Error: No Wayland or X11 display detected" >&2
	exit 1
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | "$dmenu" "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | $xdotool
fi
