#!/bin/bash

. "${XDG_CONFIG_HOME:-$HOME/.config}/sh/shutil.sh"

CARDPATH="/sys/class/drm/card0/device"

do_set() {
    case "$1" in
        bat*)
            run_elevated sh -c "echo battery > $CARDPATH/power_dpm_state"
            ;;
        bal*)
            run_elevated sh -c "echo balanced > $CARDPATH/power_dpm_state"
            ;;
        per*)
            run_elevated sh -c "echo performance > $CARDPATH/power_dpm_state"
            ;;
        a*)
            run_elevated sh -c "echo auto > $CARDPATH/power_dpm_force_performance_level"
            ;;
        l*)
            run_elevated sh -c "echo low > $CARDPATH/power_dpm_force_performance_level"
            ;;
        h*)
            run_elevated sh -c "echo high > $CARDPATH/power_dpm_force_performance_level"
            ;;
        *)
            do_usage
            ;;
    esac
}

do_get() {
    echo -n "power_dpm_state: "; cat "$CARDPATH/power_dpm_state"
    echo -n "power_dpm_force_performance_level: "; cat "$CARDPATH/power_dpm_force_performance_level"
}

do_usage() {
    echo "Usage: $(basename "$0") [get|set [battery|balanced|performance|auto|low|high|bat|bal|per|a|h|l]]"
    exit 1
}

case "$1" in
    "set")
        shift
        for VAR in "$@"; do
          do_set "$VAR"
        done
        do_get
        ;;
    "get")
        do_get
        ;;
    *)
        do_usage
        ;;
esac

exit 0
