#!/bin/sh
[ -d "$1" ] && cd $1
[ -f "$1" ] && cd $(realpath $(dirname $1))
root="$(git rev-parse --show-toplevel 2>/dev/null)"
while [[ true ]]; do
    [ "$(basename $PWD)" == "src" ] && echo "$PWD" && exit;
    [ "$PWD" == "$root" ] && echo "$PWD" && exit;
    [ "$PWD" == "/" ] && echo "$1" && exit;
    cd ..
done
