#!/bin/sh
if [ -z "$dotfiles" ]; then 
    notify-send "\$dotfiles not defined 👎" 
    exit 1
fi

if [ "$1" != "selfexec" ]; then
    exec setsid "$0" selfexec "$@"
fi

LOCKFILE="/tmp/screenshot.lock"
if [ -f "$LOCKFILE" ]; then
    old_pid=$(cat "$LOCKFILE")
    kill -TERM -"$old_pid" 2>/dev/null
    rm -f "$LOCKFILE"
    shotgun - | xclip -t 'image/png' -selection clipboard
    notify-send -t 1000 "Screenshot Taken 📸"
    setsid ffplay -nodisp -autoexit "$dotfiles/media/camera.ogg" &
    exit 0
else
    echo $$ > "$LOCKFILE"
    trap 'rm -f "$LOCKFILE"' EXIT
    #selection=$(hacksaw -f "%g")
    selection="$(hacksaw -f "%i %g")"
    window_id="$(echo "$selection" | cut -d' ' -f1)"
    geometry="$(echo "$selection" | cut -d' ' -f2)"
    shotgun -i "$window_id" -g "$geometry" - | xclip -t 'image/png' -selection clipboard
    rm -f "$LOCKFILE"
    exit 0
fi
