#!/bin/bash
[ -z "$bin" ] && (echo "\$bin not defined"; exit 1)
VIDEO_DIR="$HOME/Videos/youtube"
LOG_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles"
LOG_FILE="$LOG_DIR/tsp_ytdlp.log"
COOKIES="$HOME/source/private/cookies.firefox-private.txt"
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$LOG_FILE"
}
mkdir -p "$VIDEO_DIR"
mkdir -p "$LOG_DIR"
url="$1"
if [ -z "$url" ]; then
    notify-send "Error: No URL provided 😠"
    exit 1
fi
if [[ ! "$url" =~ ^https?:// ]]; then
    notify-send "Error: Not a URL - $url 👎👎"
    exit 1
fi
notification_id=$(echo "$url" | md5sum | cut -d' ' -f1)
notification_hint="string:x-canonical-private-synchronous:$notification_id"
is_url_already_queued() {
    local url="$1"
    tsp -l | grep -q "$url"
    return $?
}
if is_url_already_queued "$url"; then
    notify-send -t 1200 -h "$notification_hint" "URL already queued: $url 🕺"
    log "Skipped adding duplicate URL to queue: $url"
    exit 0
fi
notify-send -t 0 -h "$notification_hint" "Processing: $url 🔄"

if ! title=$(yt-dlp --print filename --cookies "$COOKIES" "$url" -o "%(channel)s_%(title)s"); then
    log "Failed to get filename for $url"
    notify-send -t 3000 -h "$notification_hint" "Failed to get filename for $url ❌"
    exit 1
fi
mkdir -p /tmp/tsp/
tsp -L "yt-dlp: $title | $url" "$bin/_tsp_download_video_helper" "$url"
tsp_exit_code="$?"
if [ $tsp_exit_code -ne 0 ]; then
    log "ERROR: Failed to queue download. TSP exit code: $tsp_exit_code - $url -> $title"
    notify-send -t 3000 -h "$notification_hint" "Error: Failed to queue download 🤯 -> $title"
    exit "$tsp_exit_code"
else
    log "Successfully queued tsp command for: $url -> $title"
    notify-send -t 3000 -h "$notification_hint" "Download queued: $title 🏃‍♂️"
fi
