#!/bin/sh
#runs all the shell scripts with file extension '.sh'
dir="$(dirname "$(readlink -f "$0")")" #foldername 
for file in "$dir"/*.sh; do 
    [ ! -x "$file" ] && echo "Nothing to run" && break  # handle the case of no *.sh
    echo "$(basename "$file")" | sed s/\.sh// | xargs pkill -9 #kill the process if its already running
    echo "Starting $file..." && $file 2>/dev/null & 
done

