vim.opt.softtabstop = 4
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
require('user.autoformat')
require('user.snacks')
require('user.colorscheme')
require("user.utils")
require("user.autoread")
require("user.keybinds")
require("user.font")
require('user.cmp').setup()
require('impatient')
require("telescope").load_extension("lazygit")
require('user.git')
require("user.oil")
require('user.telescope-settings')
require("telescope").load_extension("ui-select")
require('user.treesitter-context')
require('user.treesitter-settings')
require('user.statusline')
require('user.dap')
require('user.gigatextstreaming')
require('user.folds')
require('user.diff_applier')
require('user.markdown')
--require('user.llm').setup()
require('user.tmux')
require('user.sudavim')
require('user.title')
require('user.leadercopy')
local opts = require("user.lsp")
require('user.languages.rust').setup(opts)
require('user.languages.toml').setup(opts)
require('user.languages.python')
require('user.languages.make')
require('user.languages.nix')
require('user.mason').setup()
